### ISSUE TITLE
PostProcessing issue

### ISSUE THREAD

**Issue by NEONKID** [ncoudray/DeepPATH#35]
Hi. I used the following command to use Heatmap in this repository.

```bash
python3 0f_HeatMap_nClasses.py --image_file '/data/Genomic/asian_sort_512' --tiles_overlap 0 --output_dir '/data/Genomic/heatmap_sample' --tiles_stat '/data/Genomic/Manifest_Cancer10RandomSampling.txt' --resample_factor 10 --slide_filter 'TCGA-57-1993' --tiles_size 256
```

The contents of the tiles_stat parameter-compliant file are as follows:
```txt
TCGA-04-1348-01A-01-TS1.ffb07f65-72b7-494c-abf8-c94d8007321b.svs
TCGA-61-2610-02A-01-TS1.aade8dd8-10dc-446d-a06b-39baf5dc92d2.svs
```
However, when I run it, I get an error that the Heatmap_divider variable is not declared. What is the problem?

```python
sub_dirs:
['/data/Genomic/asian_sort_512/cancer', '/data/Genomic/asian_sort_512/Solid_Tissue_Normal']
Traceback (most recent call last):
  File "0f_HeatMap_nClasses.py", line 577, in <module>
    main()
  File "0f_HeatMap_nClasses.py", line 491, in main
    skip = saveMap(HeatMap_divider, HeatMap_0, WholeSlide_0, SlideRootName, NewSlide, dir_name)
UnboundLocalError: local variable 'HeatMap_divider' referenced before assignment
```

**Comment by ncoudray** [comment]
Hi,

  The image file should be the folder where the sorting was done, aka the tiled images
  The tile_stat file is the output of the test run (out_filename_Stats.txt)

Best,
Nicolas
